---

  - name: Calculate target Trusted vector
    set_fact:
      target_trusted_vector: "{{ sriov_vector | regex_replace('[0-9]{2}', '1') | regex_replace ('[1-9]', '1') }}" 

  - name: Set trusted vector
    block:

    - name: resulting trust vector
      debug:
        msg: "{{ target_trusted_vector }}"

    - name: Set SRIOV trust vector
      shell: esxcli system module parameters set -m i40en -a -p "trust_all_vfs={{ target_trusted_vector }}"
      register: trust_vector_cmd

    when: (current_trusted_vector is defined) and (current_trusted_vector != target_trusted_vector)
